### PR TITLE
Version bump and pod updates for tvOS support release

### PR DESCRIPTION
**Pull request by addb**
## Description
Simulator Screen Shot - Apple TV 4K (3rd generation) (at 1080p) - 2023-02-17 at 11 24 41

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cacheung** [comment]
Need to update for podspec as well?
https://github.com/addb/aepsdk-edgeidentity-ios/blob/dev/AEPEdgeIdentity.podspec#L3

**Review by cacheung — COMMENTED** [review]
Need to update for podspec as well?
https://github.com/addb/aepsdk-edgeidentity-ios/blob/dev/AEPEdgeIdentity.podspec#L3

**Review by cacheung — APPROVED** [review]

**Review by emdobrin — COMMENTED** [review]
@addb thanks for the updates. Do we already have tests and test app support for the tvOS target for this extension?

**Comment by addb** [comment]
> @addb thanks for the updates. Do we already have tests and test app support for the tvOS target for this extension?

yes

> @addb thanks for the updates. Do we already have tests and test app support for the tvOS target for this extension?

yes ✌️

**Pull request merged**
